import type { Lang, Status } from './types'

export const I18N = {
  zh: {
    board: 'Pods 看板', agents: 'Agents 列表', skillsNav: 'SKILLS 统计', tokenUsageNav: 'Token 用量', demo: '演示数据 · 未连接',
    themeMode: '主题模式', themeSystem: '系统', themeLight: '浅色', themeDark: '深色',
    ro_skill: '7天新发现', ro_assets: 'Skill 资产', ro_live: '在线', newSkillsLinkLabel: '查看 7 天新发现 Skill 名单', newSkillsScope: '新发现名单', newSkillsSummary: '新发现', clearScope: '清除名单',
    pods: 'Mission Pods', running: '运行', of: '共', dispatcher: '调度员', squad: '编队', live: '在线', feed: '活动流', silent: '静默中…', noPods: '尚无 Pod 上报', noPodsH: '成员入职后在此出现',
    skillsRank: 'Skills 排行', skillName: 'Skill', skill7: '7 天', skill30: '30 天', skillTotal: '累计', skillUsers30: '人数', skillLast: '最近', skillEquipped: '装备', noSkills: '暂无 Skill 使用数据', noSkillsH: '新版 shim 上报后在此出现',
    th_agent: 'Agent', th_disp: '调度员', th_rt: '运行时', th_model: '模型', th_status: '状态', th_today: '今日活跃', th_skill: 'Skill', th_mcp: 'MCP', th_shim: 'Shim', th_q: '成功率',
    back: '返回列表', about: '这个 Agent 擅长什么', note: '调度员上手提示', configins: '配置与指令', recent: '代表性产出', trend7: '近 7 天活跃', trend30: '近 30 天活跃', trend180: '近 180 天活跃', trend12: '近 12 周活跃', less: '少', more: '多', quality: '质量与效率', skills: 'Skill 资产', mcp: '已接 MCP',
    models: '模型', keycfg: '关键配置', insgist: '系统指令', today: '今日', week: '本周',
    q_runs: '运行次数', q_succ: '成功率', q_auto: '自动完成率', q_avg: '平均时长', q_err: '报错', q_reuse: '被复用',
    local: '本域', cross: '跨域', pit: '避坑经验', none: '暂无',
    copy: '复制能力与资产', copied: '已复制能力清单到剪贴板', copyHint: '复制该 agent 的可复刻清单(运行时/模型/配置/Skill/MCP)。',
    capability: '能力与擅长', src_cfg: '系统配置', from_cfg: '源 · 系统配置', from_mem: '源 · 记忆文件',
    access: '触达面与权限', a_shell: 'Shell 权限', a_auto: '自动批准', a_net: '网络', a_mcp: '外部服务(MCP)',
    memory: '记忆沉淀', m_updated: '更新于', m_conv: '约定', m_learn: '已学到', no_mem: '未接入记忆文件', no_mem_h: '该 agent(多为云端黑盒)未连接 memory 文件,仅有运行数据。',
    gb_reach: '触达', gb_mem: '记忆', gb_risk: '权限风险', risk_ok: '常规', risk_warn: '需关注', shim: 'shim', shimOld: '旧 shim', shimUnknown: '等待客户端心跳', cfg_shim: 'Shim 版本', cfg_ver: '类型 / 版本', cfg_role: '角色', cfg_loc: '安装位置', cfg_term: '终端', cfg_im: '集成 IM', tools: '工具集成', skills_inst: '技能(已装 Skill)', noAgent: '未找到该 agent。',
    skillsStats: 'SKILLS 统计', dailyUsed: '每日使用', dailyByOperator: '每日使用 · 按人', dailyBySkill: '每日使用 · 按 Skill', skillSearch: '搜索 skill 名', operatorSearch: '搜索操作员', runtimeFilter: 'runtime', sourceFilter: '来源', windowFilter: '时间窗', all: '全部', allTime: '全部', other: '其它', chartTotal: '合计', inProgress: '今日进行中', noChartData: '当日无使用', mainRank: '使用排行', operatorRank: '操作员排行', operatorName: '操作员', viewBy: '视角', viewSkill: '按 Skill', viewOperator: '按人', viewSkillHint: '按 Skill:看哪个能力最热', viewOperatorHint: '按人:看谁用得最多', skillsUsed: '用过 skill', sessionCount: '会话', operatorMetricNote: '口径 = 会话 × skill 去重使用次数,不是真实调用次数;只统计 used,不含 equipped。', governanceLens: '管理者筛选', lensAllSkills: '全部 Skill', lensUntrackedUsage: '未收录使用占比', untrackedUsageNote: 'source=非公司库 used 会话 / 全部 used 会话', usageShare: '占比', usedSessions: 'used 会话', noUntrackedSkills: '暂无未收录使用数据', noUntrackedSkillsH: '当前时间窗内没有非公司库 used 记录', noOperators: '暂无操作员使用数据', noOperatorsH: '只有 used 上报且 operator 非空的会话会出现在这里', companyFunnel: '公司库采纳漏斗', catalogCollected: 'catalog 收录', installed: '已安装', used30: '30 天有人使用', idleSkills: '已安装未使用', installedSnapshot: '已安装 = 各 agent 最新 profile 快照,不是历史累计', catalogUnavailable: '公司库目录不可达', catalogStale: '目录缓存已过期', source_own: 'own', source_meta: 'meta', source_external: 'external', source_non_catalog: '非公司库', trend: '趋势', runtimeDist: 'runtime 分布', operatorDist: 'operator 分布', skillBreakdown: '用过哪些 skill', skillRank: '使用 Skill 排行', first: '首见', equippedSessions: '装备态会话', equippedNote: '仅 OpenClaw:带了 ≠ 用了,不计入使用数', recentRecords: '最近记录', mode: '模式', session: 'session', skillNotFound: '未找到该 skill。', operatorNotFound: '未找到该操作员。', loading: '加载中…', loadError: '加载失败', cancel: '取消', clear: '清空', refresh: '刷新',
    notFoundHint: '当前路径没有对应页面。',
    window_today: '今天', window_this_week: '本周', window_last_week: '上周', window_7d: '近 7 天', window_14d: '近 14 天', window_30d: '近 30 天', window_90d: '近 90 天', window_custom: '自定义',
    window_period_today: '今天', window_period_this_week: '本周', window_period_last_week: '上周', window_period_7d: '近 7 天', window_period_14d: '近 14 天', window_period_30d: '近 30 天', window_period_90d: '近 90 天', window_period_custom: '自定义周期',
    changesSuffix: '变化', usedInWindow: '{window}使用', zeroUsageInWindow: '{window} 0 次', triggersInWindow: '{window}触发', previousWindow: '上期', byOperatorSuffix: '按人',
    skillsControls: '控制条', hideZeroUsage: '隐藏 0 使用', filterAction: '筛选', customStart: '开始', customEnd: '结束', allRuntime: '全部 runtime', allSource: '全部来源', allRuntimeSource: '全部 runtime/source',
    kpiPeriodChange: '时间窗变化', kpiTotalTriggers: '总触发次数', kpiCoverage: '公司库覆盖率', kpiActiveOperators: '活跃操作员数', kpiAvgSkillPerSession: '平均 skill/会', kpiPublishedSkills: '新增发布 Skill', kpiUntrackedShare: '未收录占比', kpiIdleSkills: '闲置 Skill 数', kpiUnusedRatio: '装了没用比例', kpiTop3Share: 'Top3 集中度', usageRecords30d: '30d 使用记录', activeRate7d: '7d 活跃率', avgSkillsPerOperator: '人均 skill', avgSessionsPerOperator: '人均会话', runtimeCoverage: 'runtime 覆盖', sourceCoverage: '来源覆盖', snapshot: '快照',
    records: '条记录', operatorsUnit: '人', skillsUnit: '个 skill', categoryUnit: '类', perSession: '/会', inUse: '有使用', usedByCompany: '公司库 skill 有使用记录', top3Concentrated: '使用集中在 Top3 skill', avgPrefix: '平均', autoUsed: '正在被自发使用', installedUnusedText: '装了但窗口内没用',
    publishedSkillsTitle: '新增发布 Skill', publishedSkillsSubtitle: '公司库 own/meta · 按发布时间统计', publishedSkillsEmpty: '当前时间窗没有新发布 Skill', publishedSkillsEmptyHint: '切换时间窗或等待公司库 catalog 同步后再查看', publishedAt: '发布时间', updatedAt: '更新时间', author: '作者', windowUsage: '窗口使用', publishedCount: '个新发布',
    healthIssues: '问题线索', usageSignals: '使用线索', todoSignals: '待处理线索', heavyUsers: '重度使用者', sleeping7d: '近 7 天沉睡', lowCoverageUsers: '低覆盖使用者', untrackedUsed: '有使用但未收录', installedUnused: '装了没用', catalogZeroInstall: '收录但零装机',
    healthUntrackedAction: '看未收录 used 名单', healthUnusedAction: '看已装未用名单', healthCoverageAction: '看有记录的公司库 skill', healthTop3Action: '看集中使用分布', healthAverageAction: '看会话使用分布', healthOperatorsAction: '看操作员名单', healthRuntimeAction: '看 runtime 分布', healthSourceAction: '看来源分布',
    viewEvidence: '查看记录', viewRawRecords: '查看记录', viewList: '查看名单', viewByOperatorEvidence: '按使用者分组', ignoreInPage: '忽略', moreActions: '更多动作', restoreIgnored: '恢复已忽略', noTodo: '暂无待办', showAll: '查看全部', expand: '展开', collapse: '收起', installs: '装机', zeroTimesInWindow: '0 次', cataloged: '收录', zeroInstall: '0 装机', clueUntrackedTitle: '未收录记录', clueIdleTitle: '装了没用', clueZeroInstallTitle: '零装机', installersList: '安装者名单', zeroInstallList: '零装机名单', lastUsed: '上次使用', neverUsed: '从未使用', noRecords: '暂无记录', peopleInstalled: '人安装', untrackedShort: '未收录', installedUnusedShort: '装了没用', zeroInstallShort: '零装机', allShown: '已全量展示', showingTop: '展示前', itemsUnit: '个', sourceUntracked: '未收录', sourceCompany: '公司库',
    adminTitle: '后台数据清理台', adminWarning: '硬删会进入回收站并写审计；删除只清历史，仍在上报的源头会重新出现。', adminGateTitle: '后台清理 · 管理钥匙', adminKey: 'X-TF-Admin-Key', adminEnter: '进入', adminBadKey: '管理钥匙错误，或服务端未配置 TF_ADMIN_KEY。', adminBack: '← Pods', adminExit: '退出清理台', adminExport: '导出 DB', adminExportOk: '已导出数据库快照', adminExportConfirm: '将导出整个数据库快照（含 instructions/memory/input/output 等敏感字段），不可撤销。确认导出？', adminSearch: '搜索', adminTab_operators: 'Operators', adminTab_identities: 'Identities', adminTab_sessions: 'Sessions', adminTab_skills: 'Skills', adminTab_trash: 'Trash', adminActiveOnly: '仅活跃', adminCascade: '级联子会话', adminRevoke: '同时注销 token', adminBeforeDayTitle: '按日期清理', adminBeforeOperator: '限定 operator', adminBeforeDay: '早于日期', adminBeforePreview: '预览日期清理', adminActiveSessions: '活跃会话', adminEmpty: '暂无可清理对象', adminEmptyHint: '换个搜索词或视角再试', adminName: '名称', adminScope: '范围', adminRecent: '最近', adminActive: '活跃', adminLive: '活跃', adminSelected: '已选', adminRunPreview: '预览删除影响', adminPreview: '删除预览', adminForce: '强制删除活跃会话', adminConfirmCount: '输入实际行数', adminDelete: '永久删除', adminFirstDay: 'first_day 漂移', adminIdentities: '身份清理', adminDeleted: '已删除', adminTrash: '回收站', adminTrashEmpty: '回收站为空', adminBatch: '批次', adminRows: '行数', adminStatus: '状态', adminRestored: '已恢复', adminInTrash: '在站', adminRestore: '恢复', adminRestoredOk: '已恢复批次',
    tokenUsageTitle: 'Token 用量监控', tokenUsageHint: '独立读取分发平台 KEY 用量,不改 Agent 上报协议。', tokenUsageDemo: '当前未配置真实分发平台读取凭证,页面使用演示数据。', tokenUsageConfigured: '已配置分发平台读取', tokenTotalUsage: '选择时间用量', tokenRequests: '请求数', tokenActiveKeys: '活跃 KEY', tokenErrors: '失败率', tokenRisk: '风险 KEY', tokenTrend: '用量趋势', tokenKeys: 'KEY 排行', tokenModels: '模型分析', tokenRisks: '风险提示', tokenPersonal: '个人', tokenDapp: 'Dapp', tokenOtherType: '其他', tokenOwner: '归属', tokenGroup: '分组', tokenKeyName: 'KEY 名称', tokenUsage: '用量', tokenTokens: 'Tokens', tokenRemain: '剩余额度', tokenLastUsed: '最后使用', tokenTopModel: '常用模型', tokenKind: '类型', tokenStatus: '状态', tokenAllKinds: '全部类型', tokenAllGroups: '全部分组', tokenAllModels: '全部模型', tokenSearch: '搜索 KEY / 归属', tokenNormal: '正常', tokenLowQuota: '额度偏低', tokenExhausted: '已耗尽', tokenHighError: '失败偏高', tokenDisabled: '停用/异常', tokenUnlimited: '不限额', tokenNoData: '暂无用量数据', tokenNoDataHint: '配置分发平台读取凭证后会显示真实 KEY 用量。',
  },
  en: {
    board: 'Pods', agents: 'Agents', skillsNav: 'SKILLS', tokenUsageNav: 'Token usage', demo: 'Demo · offline',
    themeMode: 'Theme mode', themeSystem: 'System', themeLight: 'Light', themeDark: 'Dark',
    ro_skill: 'New in 7d', ro_assets: 'Skill assets', ro_live: 'Live', newSkillsLinkLabel: 'View new skills found in 7 days', newSkillsScope: 'New list', newSkillsSummary: 'New', clearScope: 'Clear list',
    pods: 'Mission Pods', running: 'running', of: 'of', dispatcher: 'dispatcher', squad: 'squad', live: 'live', feed: 'Activity', silent: 'quiet…', noPods: 'No pods yet', noPodsH: 'appears after onboarding',
    skillsRank: 'Skills ranking', skillName: 'Skill', skill7: '7d', skill30: '30d', skillTotal: 'Total', skillUsers30: 'Users', skillLast: 'Last', skillEquipped: 'equipped', noSkills: 'No skill usage yet', noSkillsH: 'appears after updated shims report',
    th_agent: 'Agent', th_disp: 'Dispatcher', th_rt: 'Runtime', th_model: 'Models', th_status: 'Status', th_today: 'Active today', th_skill: 'Skill', th_mcp: 'MCP', th_shim: 'Shim', th_q: 'Success',
    back: 'Back to list', about: 'What this agent is good at', note: "Dispatcher's tips", configins: 'Config & instructions', recent: 'Representative work', trend7: 'Active · last 7 days', trend30: 'Active · last 30 days', trend180: 'Active · last 180 days', trend12: 'Active · last 12 weeks', less: 'Less', more: 'More', quality: 'Quality & efficiency', skills: 'Skill assets', mcp: 'MCP servers',
    models: 'Models', keycfg: 'Key config', insgist: 'System instructions', today: 'Today', week: 'This week',
    q_runs: 'Runs', q_succ: 'Success', q_auto: 'Auto-completion', q_avg: 'Avg duration', q_err: 'Errors', q_reuse: 'Reused by',
    local: 'local', cross: 'cross', pit: 'Pitfalls learned', none: 'none',
    copy: 'Copy capability & assets', copied: 'Manifest copied to clipboard', copyHint: 'Copies a replicable manifest (runtime/models/config/skills/MCP).',
    capability: 'Capability', src_cfg: 'System config', from_cfg: 'from config', from_mem: 'from memory',
    access: 'Access & permissions', a_shell: 'Shell', a_auto: 'Auto-approve', a_net: 'Network', a_mcp: 'External services (MCP)',
    memory: 'Memory', m_updated: 'updated', m_conv: 'convention', m_learn: 'learned', no_mem: 'no memory file', no_mem_h: 'This agent (often a cloud black-box) has no memory file connected; runtime data only.',
    gb_reach: 'Reach', gb_mem: 'Memory', gb_risk: 'Permission risk', risk_ok: 'normal', risk_warn: 'review', shim: 'shim', shimOld: 'old shim', shimUnknown: 'awaiting client', cfg_shim: 'Shim version', cfg_ver: 'Type / version', cfg_role: 'Role', cfg_loc: 'Location', cfg_term: 'Terminal', cfg_im: 'IM', tools: 'Integrations', skills_inst: 'Skills installed', noAgent: 'Agent not found.',
    skillsStats: 'SKILLS stats', dailyUsed: 'Daily usage', dailyByOperator: 'Daily usage · by operator', dailyBySkill: 'Daily usage · by skill', skillSearch: 'Search skill', operatorSearch: 'Search operator', runtimeFilter: 'runtime', sourceFilter: 'source', windowFilter: 'window', all: 'All', allTime: 'All time', other: 'Other', chartTotal: 'Total', inProgress: 'today in progress', noChartData: 'No usage this day', mainRank: 'Usage ranking', operatorRank: 'Operator ranking', operatorName: 'Operator', viewBy: 'View', viewSkill: 'By skill', viewOperator: 'By operator', viewSkillHint: 'By skill: see which capabilities are hottest', viewOperatorHint: 'By operator: see who uses skills most', skillsUsed: 'Skills used', sessionCount: 'Sessions', operatorMetricNote: 'Metric = deduped session × skill usage, not actual invocation count; used only, equipped excluded.', governanceLens: 'Manager lens', lensAllSkills: 'All skills', lensUntrackedUsage: 'Untracked usage share', untrackedUsageNote: 'non-catalog used sessions / all used sessions', usageShare: 'Share', usedSessions: 'Used sessions', noUntrackedSkills: 'No untracked usage', noUntrackedSkillsH: 'No non-catalog used records in this window', noOperators: 'No operator usage yet', noOperatorsH: 'Only used rows with a non-empty operator appear here', companyFunnel: 'Company catalog funnel', catalogCollected: 'catalog', installed: 'installed', used30: 'used in 30d', idleSkills: 'installed, unused', installedSnapshot: 'Installed = latest profile snapshot per agent, not historical total', catalogUnavailable: 'catalog unreachable', catalogStale: 'catalog cache is stale', source_own: 'own', source_meta: 'meta', source_external: 'external', source_non_catalog: 'non-catalog', trend: 'Trend', runtimeDist: 'Runtime distribution', operatorDist: 'Operator distribution', skillBreakdown: 'Skills used', skillRank: 'Skill usage ranking', first: 'First seen', equippedSessions: 'Equipped sessions', equippedNote: 'OpenClaw only: equipped does not mean used, and is not counted above', recentRecords: 'Recent records', mode: 'Mode', session: 'session', skillNotFound: 'Skill not found.', operatorNotFound: 'Operator not found.', loading: 'Loading…', loadError: 'Load failed', cancel: 'Cancel', clear: 'Clear', refresh: 'Refresh',
    notFoundHint: 'No page matches this path.',
    window_today: 'Today', window_this_week: 'This week', window_last_week: 'Last week', window_7d: 'Last 7 days', window_14d: 'Last 14 days', window_30d: 'Last 30 days', window_90d: 'Last 90 days', window_custom: 'Custom',
    window_period_today: 'Today', window_period_this_week: 'This week', window_period_last_week: 'Last week', window_period_7d: 'Last 7 days', window_period_14d: 'Last 14 days', window_period_30d: 'Last 30 days', window_period_90d: 'Last 90 days', window_period_custom: 'Custom range',
    changesSuffix: ' changes', usedInWindow: 'Used in {window}', zeroUsageInWindow: '0 in {window}', triggersInWindow: '{window} triggers', previousWindow: 'Previous', byOperatorSuffix: 'by operator',
    skillsControls: 'Controls', hideZeroUsage: 'Hide zero usage', filterAction: 'Filters', customStart: 'Start', customEnd: 'End', allRuntime: 'All runtime', allSource: 'All sources', allRuntimeSource: 'All runtime/source',
    kpiPeriodChange: 'Window changes', kpiTotalTriggers: 'Total triggers', kpiCoverage: 'Catalog coverage', kpiActiveOperators: 'Active operators', kpiAvgSkillPerSession: 'Avg skill/session', kpiPublishedSkills: 'New published skills', kpiUntrackedShare: 'Untracked share', kpiIdleSkills: 'Idle skills', kpiUnusedRatio: 'Installed unused', kpiTop3Share: 'Top3 concentration', usageRecords30d: '30d records', activeRate7d: '7d active rate', avgSkillsPerOperator: 'Avg skills/operator', avgSessionsPerOperator: 'Avg sessions/operator', runtimeCoverage: 'Runtime coverage', sourceCoverage: 'Source coverage', snapshot: 'Snapshot',
    records: 'records', operatorsUnit: 'operators', skillsUnit: 'skills', categoryUnit: 'types', perSession: '/session', inUse: 'in use', usedByCompany: 'catalog skills used', top3Concentrated: 'Usage concentrated in Top3 skills', avgPrefix: 'Avg', autoUsed: 'is being used outside the catalog', installedUnusedText: 'installed but unused in window',
    publishedSkillsTitle: 'New published skills', publishedSkillsSubtitle: 'Company catalog own/meta · by publish time', publishedSkillsEmpty: 'No new published skills in this window', publishedSkillsEmptyHint: 'Change the window or wait for the catalog to sync', publishedAt: 'Published', updatedAt: 'Updated', author: 'Author', windowUsage: 'Window usage', publishedCount: 'published',
    healthIssues: 'Issue signals', usageSignals: 'Usage signals', todoSignals: 'Action signals', heavyUsers: 'Heavy users', sleeping7d: 'Quiet in last 7d', lowCoverageUsers: 'Low-coverage users', untrackedUsed: 'Used but uncataloged', installedUnused: 'Installed, unused', catalogZeroInstall: 'Cataloged, zero install',
    healthUntrackedAction: 'Open uncataloged used list', healthUnusedAction: 'Open installed-unused list', healthCoverageAction: 'Open catalog skills with records', healthTop3Action: 'Open concentration breakdown', healthAverageAction: 'Open session usage breakdown', healthOperatorsAction: 'Open operator list', healthRuntimeAction: 'Open runtime breakdown', healthSourceAction: 'Open source breakdown',
    viewEvidence: 'View records', viewRawRecords: 'View records', viewList: 'View list', viewByOperatorEvidence: 'Group by operator', ignoreInPage: 'Ignore', moreActions: 'More actions', restoreIgnored: 'Restore ignored', noTodo: 'No action items', showAll: 'Show all', expand: 'Expand', collapse: 'Collapse', installs: 'installs', zeroTimesInWindow: '0', cataloged: 'cataloged', zeroInstall: 'zero install', clueUntrackedTitle: 'Uncataloged records', clueIdleTitle: 'Installed, unused', clueZeroInstallTitle: 'Zero install', installersList: 'Installers', zeroInstallList: 'Zero-install list', lastUsed: 'Last used', neverUsed: 'Never used', noRecords: 'No records', peopleInstalled: 'installed', untrackedShort: 'uncataloged', installedUnusedShort: 'installed unused', zeroInstallShort: 'zero install', allShown: 'all shown', showingTop: 'showing top', itemsUnit: 'items', sourceUntracked: 'uncataloged', sourceCompany: 'company catalog',
    adminTitle: 'Admin data cleanup', adminWarning: 'Hard deletes go to trash and audit; cleanup removes history only, live reporters can recreate data.', adminGateTitle: 'Admin cleanup · key required', adminKey: 'X-TF-Admin-Key', adminEnter: 'Enter', adminBadKey: 'Bad admin key, or TF_ADMIN_KEY is not configured on the server.', adminBack: '← Pods', adminExit: 'Exit cleanup', adminExport: 'Export DB', adminExportOk: 'Database snapshot exported', adminExportConfirm: 'This exports a snapshot of the ENTIRE database (including sensitive instructions/memory/input/output) and cannot be undone. Export now?', adminSearch: 'Search', adminTab_operators: 'Operators', adminTab_identities: 'Identities', adminTab_sessions: 'Sessions', adminTab_skills: 'Skills', adminTab_trash: 'Trash', adminActiveOnly: 'Active only', adminCascade: 'Cascade children', adminRevoke: 'Revoke token too', adminBeforeDayTitle: 'Date cleanup', adminBeforeOperator: 'Operator scope', adminBeforeDay: 'Before date', adminBeforePreview: 'Preview date cleanup', adminActiveSessions: 'Active sessions', adminEmpty: 'No cleanup objects', adminEmptyHint: 'Try another search or view', adminName: 'Name', adminScope: 'Scope', adminRecent: 'Recent', adminActive: 'Active', adminLive: 'live', adminSelected: 'Selected', adminRunPreview: 'Preview impact', adminPreview: 'Delete preview', adminForce: 'Force active sessions', adminConfirmCount: 'Enter row count', adminDelete: 'Delete permanently', adminFirstDay: 'first_day drift', adminIdentities: 'Identities', adminDeleted: 'Deleted', adminTrash: 'Trash', adminTrashEmpty: 'Trash is empty', adminBatch: 'Batch', adminRows: 'Rows', adminStatus: 'Status', adminRestored: 'Restored', adminInTrash: 'In trash', adminRestore: 'Restore', adminRestoredOk: 'Batch restored',
    tokenUsageTitle: 'Token usage monitor', tokenUsageHint: 'Read-only mirror of distribution key usage, separate from agent telemetry.', tokenUsageDemo: 'Real distribution credentials are not configured; showing demo data.', tokenUsageConfigured: 'Distribution reader configured', tokenTotalUsage: 'Usage in window', tokenRequests: 'Requests', tokenActiveKeys: 'Active keys', tokenErrors: 'Error rate', tokenRisk: 'Risk keys', tokenTrend: 'Usage trend', tokenKeys: 'Key ranking', tokenModels: 'Model analysis', tokenRisks: 'Risk alerts', tokenPersonal: 'Personal', tokenDapp: 'Dapp', tokenOtherType: 'Other', tokenOwner: 'Owner', tokenGroup: 'Group', tokenKeyName: 'Key name', tokenUsage: 'Usage', tokenTokens: 'Tokens', tokenRemain: 'Remaining', tokenLastUsed: 'Last used', tokenTopModel: 'Top model', tokenKind: 'Type', tokenStatus: 'Status', tokenAllKinds: 'All types', tokenAllGroups: 'All groups', tokenAllModels: 'All models', tokenSearch: 'Search key / owner', tokenNormal: 'Normal', tokenLowQuota: 'Low quota', tokenExhausted: 'Exhausted', tokenHighError: 'High errors', tokenDisabled: 'Disabled / abnormal', tokenUnlimited: 'Unlimited', tokenNoData: 'No usage data', tokenNoDataHint: 'Configure distribution reader credentials to show real key usage.',
  },
} as const

export const ST = {
  zh: { running: '运行中', started: '启动', waiting: '等待', blocked: '受阻', error: '错误', done: '完成', idle: '空闲' },
  en: { running: 'running', started: 'started', waiting: 'waiting', blocked: 'blocked', error: 'error', done: 'done', idle: 'idle' },
} as const

export function makeT(lang: Lang) {
  return (key: string) => I18N[lang][key as keyof typeof I18N.zh] || key
}

export function statusName(lang: Lang, status: Status) {
  return (ST[lang] as Record<string, string>)[status] || status
}
