import './theme.test.ts'
import './timeFormat.test.ts'
import './skillsDashboard.test.ts'
import './skillsEvidence.test.ts'
import './skillNames.test.ts'
import './skillsPresentation.test.ts'
import './skillsCopy.test.ts'
import './agentsDashboard.test.ts'
import './tokenUsageQuery.test.ts'
import './operatorDetailQuery.test.ts'
import './operatorDetailAnalysis.test.ts'
import '../components/skills/OperatorSkillAnalysis.test.tsx'
import { runApiCacheTests } from './apiCache.test.ts'

await runApiCacheTests()
